[tool.poetry]
name = "wave-viewer"
version = "0.1.0"
description = "A simple GUI for viewing waveforms."
authors = ["Jiahao Yuan <kaho0769@qq.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kahojyun/wave-viewer"
packages = [{include = "wave_viewer"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
vispy = "^0.13.0"
pyside6 = "^6.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
